name = "cloudpaste"
main = "worker.js"
compatibility_date = "2024-11-27"

workers_dev = true

[[kv_namespaces]]
binding = "PASTE_STORE"
id = "74dda65b33704e7c90cb44724072515c"

[[kv_namespaces]]
binding = "UPLOAD_STATUS"
id = "5c6441e175c54661af7a1a4f15469efb"

[[r2_buckets]]
bucket_name = "cloudpaste-files"
binding = "FILE_STORE"
